import assert from "node:assert/strict";
import test from "node:test";

import { hasSubstantiveReleaseNoteText } from "../scripts/release-note-content.mjs";

const asciiPunctuation = Array.from({ length: 94 }, (_, index) => String.fromCodePoint(index + 33))
  .filter((character) => /^[\p{P}\p{S}]$/u.test(character));
const nonIgnorableFormatCodePoints = [
  0x600, 0x601, 0x602, 0x603, 0x604, 0x605, 0x6DD, 0x70F, 0x890, 0x891, 0x8E2,
  0xFFF9, 0xFFFA, 0xFFFB, 0x110BD, 0x110CD, 0x13430, 0x13431, 0x13432, 0x13433,
  0x13434, 0x13435, 0x13436, 0x13437, 0x13438, 0x13439, 0x1343A, 0x1343B, 0x1343C,
  0x1343D, 0x1343E, 0x1343F,
];

const referenceOnlyNotes = [
  ["URL obfuscated with combining grapheme joiner", "h\u034Fttps://example.test/release"],
  ["URL obfuscated with variation selector", "h\uFE0Fttps://example.test/release"],
  ["URL obfuscated with Mongolian variation selector", "h\u180Bttps://example.test/release"],
  ["fullwidth URL", "ｈｔｔｐｓ：／／example.test/release"],
  ["HTTP URL", "https://example.test/release"],
  ["Gopher URL", "gopher://example.test/1/releases"],
  ["empty HTTPS scheme", "https:"],
  ["empty mailto scheme", "mailto:"],
  ["empty URN scheme", "urn:"],
  ["mailto URI", "mailto:release@example.test"],
  ["data URI", "data:text/plain,release"],
  ["URN", "urn:example:release"],
  ["network-path reference", "//example.test/release"],
  ["absolute-path reference", "/releases"],
  ["Windows absolute-path reference", "C:\\releases"],
  ["current-directory reference", "./releases"],
  ["parent-directory reference", "../releases"],
  ["bare current directory", "./"],
  ["bare parent directory", "../"],
  ["fragment reference", "#release"],
  ["bare fragment marker", "#"],
  ["query reference", "?release=2.1.1"],
  ["bare query marker", "?"],
  ["repository path", "owner/repository"],
  ["ambiguous lowercase repository path", "client/project"],
  ["SCP-style Git reference", "git@example.test:owner/repo"],
  ["ASCII bare domain", "example.test/release"],
  ["www domain", "www.example.test/release"],
  ["ideographic-dot IDN", "例え。テスト/リリース"],
  ["fullwidth-dot IDN", "例え．テスト/リリース"],
  ["halfwidth-dot IDN", "例え｡テスト/リリース"],
  ["Devanagari IDN", "उदाहरण.भारत/रिलीज"],
  ["punycode domain and TLD", "xn--r8jz45g.xn--zckzah/release"],
  ["full IPv6", "2001:0db8:0000:0000:0000:ff00:0042:8329"],
  ["compressed IPv6", "2001:db8::ff00:42:8329"],
  ["loopback IPv6", "::1"],
  ["bracketed IPv6 with port", "[::1]:3000/release"],
  ["canonical IPv4", "127.0.0.1:3000/release"],
  ["short IPv4", "127.1"],
  ["hexadecimal IPv4", "0x7f000001"],
  ["single-integer IPv4", "2130706433"],
  ["localhost", "localhost:3000/release"],
  ["localhost.localdomain", "localhost.localdomain"],
  ["localhost domain prefix", "localhost.example.test"],
  ["IPv4 domain prefix", "127.0.0.1.example.test"],
  ["domain email", "release@example.test"],
  ["localhost email", "release@localhost"],
  ["IPv4 email", "release@127.0.0.1"],
  ["bracketed IPv4 email", "release@[127.0.0.1]"],
  ["bracketed IPv6 email", "release@[::1]"],
  ["RFC IPv6 email literal", "release@[IPv6:::1]"],
  ["full RFC IPv6 email literal", "release@[IPv6:2001:db8::1]"],
  ["IDN email", "release@例え.テスト"],
  ["ideographic-dot IDN email", "release@例え。テスト"],
  ["punycode email", "release@xn--r8jz45g.xn--zckzah"],
  ["localhost.localdomain email", "release@localhost.localdomain"],
  ["localhost prefix email", "release@localhost.example.test"],
  ["IPv4 prefix email", "release@127.0.0.1.example.test"],
  ["single-label email", "release@internal"],
  ["single-label IDN email", "release@例え"],
  ["single-label punycode email", "release@xn--r8jz45g"],
  ["single-label SCP host", "git@internal:owner/repo"],
  ["single-label IDN SCP host", "git@例え:owner/repo"],
  ["single-label punycode SCP host", "git@xn--r8jz45g:owner/repo"],
  ["IPvFuture literal", "[v1.fe80::]"],
  ["IPvFuture email literal", "release@[v1.fe80::]"],
  ["ASCII parenthesis wrapper", "(https://example.test/release)"],
  ["ASCII square wrapper", "[https://example.test/release]"],
  ["ASCII brace wrapper", "{https://example.test/release}"],
  ["ASCII angle wrapper", "<https://example.test/release>"],
  ["Unicode Ps/Pe wrapper", "❨https://example.test/release❩"],
  ["Unicode Pi/Pf double quotes", "“https://example.test/release”"],
  ["Unicode Pi/Pf single quotes", "‘https://example.test/release’"],
  ["guillemets", "«https://example.test/release»"],
  ["single guillemets", "‹https://example.test/release›"],
  ["CJK corner wrapper", "「https://example.test/release」"],
  ["CJK white corner wrapper", "『https://example.test/release』"],
  ["CJK lenticular wrapper", "【https://example.test/release】"],
  ["CJK angle wrapper", "〈https://example.test/release〉"],
  ["CJK double-angle wrapper", "《https://example.test/release》"],
  ["fullwidth parenthesis wrapper", "（https://example.test/release）"],
  ["fullwidth square wrapper", "［https://example.test/release］"],
  ["fullwidth brace wrapper", "｛https://example.test/release｝"],
  ["fullwidth angle wrapper", "＜https://example.test/release＞"],
  ["nested mixed wrappers", "《{[https://example.test/release]}》"],
  ["wrapped default-ignorable URL", "「h\u034Fttps://example.test/release」"],
  ["semicolon-separated references", "example.test;mailto:release@example.test"],
  ["comma-separated references", "example.test,127.1"],
  ["pipe-separated references", "example.test|//other.example.test"],
  ["ampersand-separated references", "example.test&urn:example:release"],
  ["plus-separated references", "example.test+127.1"],
  ["equals-separated references", "example.test=localhost"],
  ["tilde-separated references", "example.test~[::1]"],
  ["underscore-separated references", "example.test_//other.example.test"],
  ["Unicode-ellipsis-separated references", "example.test…mailto:release@example.test"],
  ["ASCII-ellipsis-separated references", "example.test...mailto:release@example.test"],
  ["percent-separated references", "example.test%localhost"],
  ["percent-encoded path between references", "example.test%2Flocalhost"],
  ["unclosed wrapper", "{example.test"],
  ["interlinear annotation anchor", "example.test\uFFF9localhost"],
  ["repository path with query", "owner/repository?tab=readme"],
  ...asciiPunctuation.map(
    (separator) => [`ASCII U+${separator.codePointAt(0).toString(16)} between references`, `example.test${separator}localhost`],
  ),
  ...nonIgnorableFormatCodePoints.map(
    (codePoint) => [`format U+${codePoint.toString(16)} between references`, `example.test${String.fromCodePoint(codePoint)}localhost`],
  ),
  ["NEL-separated references", "example.test\u0085mailto:release@example.test"],
  ["NUL-separated references", "example.test\u0000urn:example:release"],
  ["Cc unit-separator references", "127.1\u001Fexample.test"],
  ["arbitrary URI scheme", "web+demo:opaque"],
  ["empty arbitrary URI scheme", "custom-scheme:"],
  ["capitalized empty scheme without a value", "Release:"],
  ["default-ignorable-only text", "\u034F\u180B\uFE0F"],
  ["punctuation-only text", "..."],
];

const substantiveNotes = [
  ["Node.js technology token", "Node.js"],
  ["React.js technology token", "React.js"],
  ["node:test technology token", "node:test"],
  ["npm scoped-package technology token", "npm:@scope/package"],
  ["Deno.land technology token", "Deno.land"],
  ["technology token with sentence punctuation", "Node.js."],
  ["prose with URL", "See release notes at https://example.test/release"],
  ["prose with IDN", "See release notes at 例え。テスト/リリース"],
  ["prose with email", "Report issues to release@example.test"],
  ["Node.js version prose", "Added Node.js 22 support"],
  ["Deno prose", "Improved Deno 2 compatibility"],
  ["Italian prose", "Migliorata la stabilità del rilascio"],
  ["Japanese prose", "リリースの安定性を改善"],
  ["Devanagari prose", "रिलीज़ की स्थिरता में सुधार"],
  ["Fixed label before URL", "Fixed: https://example.test"],
  ["Docs label before URL", "Docs: https://example.test"],
  ["Changed label before domain", "Changed: example.test"],
  ["Release label before path", "Release: /notes"],
  ["See label before mailto", "See: mailto:release@example.test"],
  ["glued label and URL", "Fixed:https://example.test"],
  ["em-dash label and URL", "Fixed—https://example.test"],
  ["attached parenthesized URL", "Fixed(https://example.test)"],
  ["em-dash label and domain", "Release—example.test"],
  ["human slash term", "and/or"],
  ["network acronym slash term", "TCP/IP"],
  ["delivery acronym slash term", "CI/CD"],
  ["runtime slash term", "Node.js/Deno"],
  ["language slash term", "C++/Rust"],
  ["architecture slash term", "x86/x64"],
  ["lowercase Node.js", "node.js"],
  ["uppercase Node.js", "NODE.JS"],
  ["mixed-case Node.js", "NoDe.Js"],
  ["Node fs built-in", "node:fs"],
  ["Node net built-in", "node:net"],
  ["nested Node built-in", "node:fs/promises"],
  ["bare scoped npm package", "@scope/package"],
  ["npm-prefixed scoped package", "npm:@scope/another-package"],
  ["API acronym label", "API: https://example.test"],
  ["CI acronym label", "CI: /notes"],
  ["glued API acronym label", "API:https://example.test"],
  ["Vue.js technology token", "Vue.js"],
  ["Express.js technology token", "Express.js"],
  ["C language compound", "C/C++"],
  ["Go and Rust language compound", "Go/Rust"],
  ["client/server human compound", "client/server"],
  ["read/write human compound", "read/write"],
  ["producer/consumer human compound", "producer/consumer"],
  ["glued label and prose", "Fixed:regression"],
  ["C++ namespace symbol", "std::vector"],
  ["qualified JavaScript symbol", "Promise.resolve"],
  ["glued changed label", "Changed:parser"],
  ["glued added label", "Added:Node.js"],
  ["lowercase fix label", "fix:parser"],
  ["Tokio namespace symbol", "tokio::spawn"],
  ["qualified .NET symbol", "System.Text.Json"],
  ["ASP.NET technology", "ASP.NET"],
  ["package subpath", "react-dom/client"],
  ["sync/async human compound", "sync/async"],
  ["HTTP protocol version", "HTTP/2"],
  ["TLS protocol version", "TLS/1.3"],
  ["OAuth/OIDC technology compound", "OAuth/OIDC"],
];

test("reference-only release notes fail closed across URI, host, address, email, and path forms", () => {
  for (const [name, value] of referenceOnlyNotes) {
    assert.equal(hasSubstantiveReleaseNoteText(value), false, `${name}: ${JSON.stringify(value)}`);
  }
});

test("technology names and genuine multilingual prose remain substantive", () => {
  for (const [name, value] of substantiveNotes) {
    assert.equal(hasSubstantiveReleaseNoteText(value), true, `${name}: ${JSON.stringify(value)}`);
  }
});

test("unclosed wrappers are classified in linear time", () => {
  const start = performance.now();
  assert.equal(hasSubstantiveReleaseNoteText(`${"{".repeat(16_000)}example.test`), false);
  assert.ok(performance.now() - start < 1_000, "16k unclosed wrappers should not trigger quadratic scanning");
});

test("deep balanced wrappers do not consume semantic recursion depth", () => {
  assert.equal(hasSubstantiveReleaseNoteText(`${"(".repeat(64)}real prose${")".repeat(64)}`), true);
});
